version: '2'
services:
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx.docker
        volumes:
            - ./:/var/www
            - ./docker/nginx/ssl:/etc/nginx/ssl
        ports:
        - "${NGINX_PORT}:443"
        links:
        - php-fpm
    php-fpm:
        build:
            context: ./
            dockerfile: docker/php-fpm.docker
        volumes:
            - ./:/var/www
        links:
            - mysql
            - redis
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=redis"
#    php-cli:
#        build:
#            context: ./
#            dockerfile: docker/php-cli.docker
#        volumes:
#        - ./:/var/www
#        links:
#        - mysql
#        - redis
#        environment:
#        - "DB_PORT=3306"
#        - "DB_HOST=mysql"
#        - "REDIS_PORT=6379"
#        - "REDIS_HOST=redis"
    mysql:
        image: mysql:5.7
        volumes:
            - ./storage/docker/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
            - "MYSQL_USER=${DB_USERNAME}"
            - "MYSQL_PASSWORD=${DB_PASSWORD}"
            - "MYSQL_DATABASE=${DB_DATABASE}"
        ports:
            - "33062:3306"
    
    redis:
        image: redis:3.0
        ports:
            - "63792:6379"
    
    node:
        image: node:8.6-alpine
        volumes:
        - ./:/var/www
        working_dir: /var/www
        tty: true